---
version: '3'
services:
  redirector:
    image: redirector:latest
    volumes:
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
    ports:
      - 8080:8080
    environment:
      NGINX_VHOST_TEST: "localhost:web:80:web:80:both"
  web:
    image: subfuzion/netcat
    entrypoint: nc -vlk 80
